import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import Providers from "./Providers";
import "./globals.css";

const roboto = Roboto({
  weight: ["100", "300", "400", "500", "700", "900"],
  subsets: ["latin"],
  display: "swap",
  variable: "--font-roboto",
});

export const metadata: Metadata = {
  title: "Hearthstone Card App",
  description: "Generated by Simon Partridge",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={`${roboto.variable}`}>
      <body className="bg-white dark:bg-dark1 text-dark1 dark:text-white">
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
