import PrelineInitiator from "@/Providers/PrelineProvider";
import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Hearthstone Card App",
  description: "Generated by Simon Partridge",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <PrelineInitiator />
        {children}
      </body>
    </html>
  );
}
